### ISSUE TITLE
dnd5e 2.1.1 compatibility

### ISSUE THREAD

**Issue by hedgehog8711** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#71]
Yesterday there was an update to the Dnd5e gaming system 2.1.1 and the stat block titles have disappeared. You can click on the stat and roll the save or ability check. I hope this helps and thank you in advance for your help. 

![Capture2](https://user-images.githubusercontent.com/114251484/211866330-b5de188f-e6f2-4a5c-a5ac-aa0a2475596d.PNG)

**Comment by akrigline** [comment]
Thanks, if you find anything else wierd, I'd appreciate adding to this issue

**Comment by hedgehog8711** [comment]
Will do so far everything else seems to be working as expected.
    On Wednesday, January 11, 2023 at 11:59:41 AM EST, Andrew Krigline ***@***.***> wrote:  
 
 


Thanks, if you find anything else wierd, I'd appreciate adding to this issue

**Comment by eltariel** [comment]
It also removed the names for all of the skills, and when I changed back to the default sheet all the skill proficiencies had been cleared.

It's specifically this sheet that's clearing the profs, since I restored a backup, turned off this sheet, then updated. All of the proficiencies were intact, and then when I changed a character's sheet back to this one the same thing happened to that character again.

Sorry, I didn't think to grab a screenshot.

(edit: just realised I had 2.1.2, not 2.1.1. Same issue though.)

**Comment by cgplayer2000** [comment]
![Screenshot 2023-01-22 204444](https://user-images.githubusercontent.com/10798879/213954039-0857c2db-ef58-4543-9c33-ae4cb8b2828b.jpg)
This sheet seemingly worked fine up until today's update.  Now my PCs sheets won't open.  I'm not sure what's wrong, but I've attached my console log.
I'm using v10.291 and 5e v2.1.2

**Comment by akrigline** [comment]
@cgplayer2000 I think i've just fixed that with alpha 2, i don't think you'll be able to 'update' the module to that version, but you can uninstall and reinstall with this json url:

https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/releases/download/v0.999.2/module.json

Also for anyone else watching this, give that alpha a try and let me know if anything wierd happens in latest from 5e system.

**Comment by cgplayer2000** [comment]
I did install from that URL.  Everything seems back to normal with the sheet.  Works just fine and no console messages that I can see.

**Comment by ronin-seven** [comment]
Using the alpha with 5e 2.1.4, no errors except for this deprecation warning:

Error: Defining attributable properties on sheets with the `.attributable` class and `data-property` value has been deprecated in favor of a single `data-attribution` value.
Deprecated since Version DnD5e 2.1.3
Backwards-compatible support will be removed in Version DnD5e 2.4
    at Object.logCompatibilityWarning (commons.js:1692:19)
    at CompactBeyond5eSheet._onPropertyAttribution (base-sheet.mjs:1305:21)
    at HTMLDivElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by ronin-seven** [comment]
Not sure if this was a recent change in dnd5e system or I just didn't notice this until now, but the dc bonus is already included in the dc field for all abilities in _prepareAbitlies():

	abl.dc = 8 + abl.mod + this.system.attributes.prof + dcBonus;

So now with the sheet updated to use spellSaveDcWithMods instead of system.attributes.spelldc, the "Spell DC" display value is double dipping into the bonus and showing the incorrect value.  Reverting the sheet source fixes the display issue.

Note that this is a display-only bug, spells cast with DC save display the correct DC in chat.
