### ISSUE TITLE
Compatibility with Foundry V11 and dnd5e 2.2.0

### ISSUE THREAD

**Issue by nschoenwald** [ElfFriend-DnD/foundryvtt-compactBeyond5eSheet#80]
Will this module be updated for the new releases of foundry and dnd5e? It's my favorite character sheet and I would love to keep using it!

**Comment by eastcw** [comment]
I think I have fixed all the issues my group have found with the sheet in dnd5e 2.2.0 (#81), but we aren't running Foundry 11 yet so I haven't verified it will work with that. I don't have permissions to merge my request or release a new version of the module though.

**Comment by mclearc** [comment]
Just to add to this that I'm on V11 and using the alpha release and having made the changes from @eastcw's branch I am seeing no problems -- everything is working as expected.

**Comment by JonathanAlumbaugh** [comment]
First of all, thank you for this excellent module! This sheet is by far the most well organized and intuitive (even for non-DDB players) of all that I've tried. A quick test of @eastcw's fork looks like it is fixed there. Description of the issue below:

On Foundry v11.304 / DnD5e 2.2.1 with no other modules activated (except Character Actions List). It does appear to display correctly (screenshot below), but I get an error message in the console and no roll when trying to roll any skills (str/dex/con/etc... in the top row works fine):

```
Uncaught TypeError: Cannot read properties of null (reading 'dataset')
    at CompactBeyond5eSheet._onRollSkillCheck (base-sheet.mjs:1355:60)
    at HTMLHeadingElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

![image](https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/assets/9826603/8c26b287-3dea-458a-8371-6a00d9d0c718)

![image](https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet/assets/9826603/840b74b1-5305-416d-9c30-59c48356d230)
